In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [3]:
#Load the dataset
trans_df=pd.read_csv('../data/transactions_cleaned.csv')
trans_df.head()

,trans_id,trans_datetime,cc_num,merchant,category,amt,firstname,lastname,gender,street,...,trans_day,trans_hour,time_period,fullname,high_amount_risk,night_risk,txn_per_card,freq_risk,location_risk,risk_score
0,1,2020-06-21 12:14:00,2.291160e+15,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,Sunday,12,Day,Jeff Elliott,0,0,640,1,0,1
1,2,2020-06-21 12:14:00,3.573030e+15,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,Sunday,12,Day,Joanne Williams,0,0,837,1,0,1
2,3,2020-06-21 12:14:00,3.598220e+15,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,Sunday,12,Day,Ashley Lopez,0,0,1073,1,0,1
3,4,2020-06-21 12:15:00,3.591920e+15,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,Sunday,12,Day,Brian Williams,0,0,663,1,0,1
4,5,2020-06-21 12:15:00,3.526830e+15,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,Sunday,12,Day,Nathan Massey,0,0,891,1,0,1

In [5]:
X = trans_df[['high_amount_risk','night_risk','freq_risk','location_risk','risk_score']]
y = trans_df['is_fraud']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
model = LogisticRegression(class_weight='balanced')
model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [10]:
y_prob = model.predict_proba(X_test)[:, 1]

In [11]:
df_test = X_test.copy()
df_test["actual"] = y_test
df_test["fraud_probability"] = y_prob

In [12]:
df_test["risk_score_ml"] = df_test["fraud_probability"] * 100

In [13]:
df_test["final_risk_score"] = (
    df_test["risk_score_ml"] +
    df_test["high_amount_risk"] * 10 +
    df_test["night_risk"] * 5 +
    df_test["freq_risk"] * 10 +
    df_test["location_risk"] * 8
)

In [14]:
def risk_level(score):
    if score > 80:
        return "High Risk"
    elif score > 40:
        return "Medium Risk"
    else:
        return "Low Risk"

df_test["risk_level"] = df_test["final_risk_score"].apply(risk_level)

In [15]:
def action(level):
    if level == "High Risk":
        return "Block Transaction"
    elif level == "Medium Risk":
        return "Manual Review"
    else:
        return "Approve"

df_test["action"] = df_test["risk_level"].apply(action)

In [16]:
df_test.head()

,high_amount_risk,night_risk,freq_risk,location_risk,risk_score,actual,fraud_probability,risk_score_ml,final_risk_score,risk_level,action
119106,0,0,1,0,1,0,0.173038,17.303799,27.303799,Low Risk,Approve
179292,0,0,1,0,1,0,0.173038,17.303799,27.303799,Low Risk,Approve
540729,0,0,1,0,1,0,0.173038,17.303799,27.303799,Low Risk,Approve
374360,0,0,1,0,1,0,0.173038,17.303799,27.303799,Low Risk,Approve
314574,0,1,1,0,2,0,0.293512,29.351213,44.351213,Medium Risk,Manual Review

In [17]:
df_test.to_csv("../outputs/final_fraud_risk_analysis.csv", index=False)